SIS/SIS/Controllers/ReceptionistController.cs
using SIS.Models;
using SIS.Models.Users;
using SIS.Models.Users.Agenda;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace SIS.Controllers
{
    public class ReceptionistController : Controller
    {
        // GET: Receptionist

        #region profile
        public ActionResult Receptionist_profile()
        {
            return View("Receptionist_profile", (Receptionist)Session["usuario"]);
        }

        public ActionResult ChangeProfile()
        {
            return View();
        }
        #endregion

        #region patient_accounts
        public ActionResult Register_patient()
        {
            /** DECLARAÇÃO E INICIALIZAÇÃO DAS VARIÁVEIS LOCAIS **/
            // --Declaração das variáveis locais--
            List<Type_disability> types_disability = new List<Type_disability>();
            List<Type_allergy> types_allergy = new List<Type_allergy>();
            List<Allergy> allergies = new List<Allergy>();

            // --Inicialização dos valores das variáveis declaradas--
            types_disability = Type_disability.List_types_disability();
            types_allergy = Type_allergy.List_allergy_types();
            allergies = Allergy.List_allergies();

            /** DESENVOLVIMENTO DO PROCESSO **/
            // --Passagem dos valores obtidos a ViewBags que armazenarão os mesmos para que mais tarde eles possam ser 
            // disponibilizados para visualização ao usuário--
            ViewBag.list_types_disability = types_disability;
            ViewBag.list_allergy_types = types_allergy;
            ViewBag.list_allergies = allergies;

            return View();
        }

        [HttpPost]
        public ActionResult Register_patient(Patient patient)
        {
            //CRIANDO OBJETO DE USUARIO
            Patient Pessoa = new Patient();
            Telephone telephone = new Telephone();
            Disability deficiencia = new Disability();

            //ATRIBUINDO OS VALORES 
            //Pessoa.Id = id;
            //Pessoa.Cpf = cpf;
            //Pessoa.Nome = nome;
            //Pessoa.Sobrenome = sobrenome;
            //string[] valoresData = data_nascimento.Split('/');
            //Pessoa.Data_nascimento = new DateTime(int.Parse(valoresData[2]), int.Parse(valoresData[1]), int.Parse(valoresData[0]));
            //Pessoa.Sexo = sex;
            //Pessoa.Email = email;
            //Pessoa.Senha = senha;
            //Pessoa.Nivel_acesso = "Pessoa";
            //Pessoa.Nome_mae = nome_mae;
            //Pessoa.Nome_pai = nome_pai;
            ////Pessoa.Deficiencia.Descricao = descricaoDeficiencia;
            ////Pessoa.Telefone.Numero = telefoneNumero;
            ////Pessoa.Telefone.Tipo = telefoneTipo;           
            //Pessoa.Endereco.Estado = estado;
            //Pessoa.Endereco.Cidade = cidade;
            //Pessoa.Endereco.Cep = cep;
            //Pessoa.Endereco.Bairro = bairro;
            //Pessoa.Endereco.Rua = rua;
            //Pessoa.Endereco.Numero = enderecoNumero;
            //Pessoa.Endereco.Complemento = complemento;

            //try
            //{
            //    HttpPostedFileBase arqPostado = Request.Files[0];

            //    int tamImagem = arqPostado.ContentLength; //pega o tamanho
            //    string tipoArq = arqPostado.ContentType; //pega o tipo

            //    if (tipoArq.IndexOf("jpeg") > 0 || tipoArq.IndexOf("png") > 0)
            //    {
            //        byte[] imgBytes = new byte[tamImagem];
            //        arqPostado.InputStream.Read(imgBytes, 0, tamImagem);

            //        Pessoa.Foto = imgBytes;
            //    }
            //}

            //catch (Exception erro)
            //{
            //    string msgErro = erro.Message;
            //}

            //Pessoa.Register();

            return RedirectToAction("List_patients");
        }
        #endregion

        public ActionResult List_patients()
        {
            return View(Patient.List_patients());
        }
        
        public ActionResult Edit_patient(string rg)
        {
            return View(Patient.GetInfo(rg));
        }
        //public ActionResult AlterarRecepcionista(string id)
        //{
        //    //UTILIZAR O OBJETO USUARIO PARA CHAMAR O MÉTODO BUSCA USUARIO DO MODELO
        //    List<Receptionist> Recepcionista = Receptionist.ListaRecepcionista(id);
        //    //COMPARAR PARA VER SE ENCONTRAR UM OBJETO IGUAL
        //    if (Recepcionista == null)
        //    {
        //        //MENSAGEM DE CONFIRMAÇÃO
        //        TempData["Msg"] = "Erro ao buscar Recepcionista!";
        //        //RETORNA PARA A VIEW 
        //        return RedirectToAction("ListarRecepcionista");
        //    }
        //    return View(Recepcionista);
        //}
        
        [HttpPost]
        // CONSTRUTOR COM OS ATRIBUTOS
        public ActionResult AlterarRecepcionista(string nome, string sobrenome, string sexo, string email, DateTime data_nascimento,
                                                 byte[] foto, string telefoneNumero, string descricaoDeficiencia, string enderecoNumero, string cep, string estado,
                                                 string cidade, string bairro, string rua, string complemento)
        {
            //CRIANDO OBJETO DE USUARIO
            Receptionist recepcionista = new Receptionist();
            Telephone telephone = new Telephone();
            Disability deficiencia = new Disability();

            //ATRIBUINDO O VALORES 
            recepcionista.Nome = nome;
            recepcionista.Sobrenome = sobrenome;
            recepcionista.Sexo = sexo;
            recepcionista.Email = email;
            recepcionista.Data_nascimento = data_nascimento;
            recepcionista.Foto = foto;

            //telephone.Numero = telefoneNumero;
            //deficiencia.Descricao = descricaoDeficiencia;

            recepcionista.Endereco.Numero = enderecoNumero;
            recepcionista.Endereco.Cep = cep;
            recepcionista.Endereco.Estado = estado;
            recepcionista.Endereco.Cidade = cidade;
            recepcionista.Endereco.Bairro = bairro;
            recepcionista.Endereco.Rua = rua;
            recepcionista.Endereco.Complemento = complemento;

            //CHAMA MÉTODO DO MODELO
            string res = recepcionista.Editar();
            TempData["Msg"] = res;
            // COMPARA SE ESTA CORRETO E APRESENTA A MENSAGEM DE CONFIRMAÇÃO
            if (res == "Salvo com sucesso!")
                //RETORNA PARA A VIEW 
                return RedirectToAction("ListarRecepcionista");
            else
                return View();
        }
        
        

        #region medical_appointment
        public ActionResult Book_appointment()
        {

            return View();
        }

        public ActionResult List_medical_appointments()
        {
            return View();
        }

        public ActionResult VerConsulta()
        {
            return View();
        }

        public ActionResult AlterarConsulta()
        {
            return View();
        }

        public ActionResult ExcluirConsulta()
        {
            return View();
        }
        #endregion
        public ActionResult AgendamentoConsultas(string id)
        {
            return View();
        }
        
        public ActionResult TrocarSenha()
        {
            return View();
        }

        public ActionResult Sair() // Apaga os cookies e volta para a tela de login
        {
            int aux = Request.Cookies.Count; // Para evitar loop :P
            string[] nomes = Request.Cookies.AllKeys; // Para chamar um cookie específico
            for (int i = 0; i < aux; i++)
            {
                HttpCookie myCookie = new HttpCookie(nomes[i]);
                myCookie.Expires = DateTime.Now.AddDays(-1d);
                Response.Cookies.Add(myCookie);
            }
            Request.Cookies.Clear(); // Limpa os cookies do servidor, mas não os da máquina do cliente

            return RedirectToAction("Login", "Home");
        }

        public ActionResult Register_appointment()
        {
            return View(new Appointment());
        }

        [HttpPost]
        public ActionResult Register_appointment(string data, string duracao, string especialidade, string medico, string titulo, string comentario, string paciente, string hospital)
        {
            Appointment consulta = new Appointment();

            string[] dataFragmentada = data.Split('-');
            consulta.Data = new DateTime(int.Parse(dataFragmentada[0]), int.Parse(dataFragmentada[1]), int.Parse(dataFragmentada[2]));
            
            DateTime _duracao = consulta.Data;
            string[] _duracaoFragmentada = duracao.Split(':');
            _duracao.AddHours(int.Parse(_duracaoFragmentada[0]));
            _duracao.AddMinutes(int.Parse(_duracaoFragmentada[1]));
            _duracao.AddSeconds(int.Parse(_duracaoFragmentada[2]));
            consulta.Duracao = _duracao;

            consulta.Especialidade = especialidade;

            Patient _paciente = new Patient();
            _paciente.Id = paciente;
            consulta.Patient_doctor[0] = _paciente;


            Doctor _medico = new Doctor();
            _medico.Id = medico;
            consulta.Patient_doctor[1] = _medico;

            consulta.Titulo = titulo;
            consulta.Comentario = comentario;
            consulta.Estado = false;
            consulta.Hospital.Cnes = hospital;

            consulta.AgendaConsulta();

            return RedirectToAction("Receptionist_profile");
        }
    }
}

SIS/SIS/Views/Receptionist/Book_appointment.cshtml
@{
    ViewBag.Title = "Book_appointment";
    ViewBag.user_type = "Recepcionista";
}

<!-- start page content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Agendar consulta</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li>
                        <i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="@Url.Action("Sair", "Home")">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a class="parent-item" href="">Consulta</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Agendar consulta</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card card-box">
                    <div class="card-head">
                        <header>Agendar consulta</header>
                    </div>
                    <div class="card-body" id="bar-parent">
                        <form action="#" id="form_sample_1" class="form-horizontal">
                            <div class="form-body">
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Título
                                        <span class="required"> * </span>
                                    </label>
                                    <div class="col-md-5">
                                        <input type="text" name="title" data-required="1" placeholder="Entre com o título" class="form-control input-height" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Data da consulta
                                        <span class="required"> * </span>
                                    </label>
                                    <div class="col-md-5">
                                        <div class="input-group date form_date " data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                            <input class="form-control input-height" size="16" placeholder="Data da consulta" type="text" value="">
                                            <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                        </div>
                                        <input type="hidden" id="dtp_input2" value="" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Das
                                        <span class="required"> * </span>
                                    </label>
                                    <div class="col-md-5">
                                        <div class="row">
                                            <div class="col-md-5">
                                                <input type="time" name="horario_inicial" data-required="1" placeholder="Ex: 13:45" class="form-control input-height" id="example-time-input">
                                            </div>

                                            <label class="control-label small-label col-md-2">Até</label>
                                            <div class="col-md-5">
                                                <input type="time" name="horario_final" data-required="1" placeholder="Ex: 14:15" class="form-control input-height" id="example-time-input2">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Consulting Doctor
                                        <span class="required"> * </span>
                                    </label>
                                    <div class="col-md-5">
                                        <select class="form-control input-height" name="select">
                                            <option value="">Select...</option>
                                            <option value="Category 1">Dr. Rajesh</option>
                                            <option value="Category 2">Dr. Sarah Smith</option>
                                            <option value="Category 3">Dr. John Deo</option>
                                            <option value="Category 3">Dr. Jay Soni</option>
                                            <option value="Category 3">Dr. Jacob Ryan</option>
                                            <option value="Category 3">Dr. Megha Trivedi</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Injury/Condition
                                    </label>
                                    <div class="col-md-5">
                                        <input name="creditcard" type="text" placeholder="Injury/Condition" class="form-control input-height" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Therapy Started Date
                                        <span class="required"> * </span>
                                    </label>
                                    <div class="col-md-5">
                                        <div class="input-group date form_date " data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                            <input class="form-control input-height" size="16" placeholder="date of appointment" type="text" value="">
                                            <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
                                        </div>
                                        <input type="hidden" id="dtp_input3" value="" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Note
                                    </label>
                                    <div class="col-md-5">
                                        <textarea name="address" class="form-control-textarea" placeholder="note" rows="5"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="offset-md-3 col-md-9">
                                        <button type="submit" class="btn btn-info m-r-20">Submit</button>
                                        <button type="button" class="btn btn-default">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->

SIS/SIS/Views/Receptionist/List_patients.cshtml
@model IEnumerable<SIS.Models.Users.Patient>

@{
    ViewBag.Title = "Listar pacientes";
    ViewBag.user_type = "Recepcionista";
}

<!-- start page content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Listar Pacientes</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li>
                        <i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="@Url.Action("Sair", "Home")">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a class="parent-item" href="">Pacientes</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Listar pacientes</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <ul class="nav customtab nav-tabs" role="tablist">
                        <li class="nav-item"><a href="#tab1" class="nav-link active" data-toggle="tab">Ver lista</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-topline-red">
                                        <div class="card-head">
                                            <header></header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6 col-xs-6">
                                                    <div class="btn-group">
                                                        <a href="@Url.Action("Register_patient", "Receptionist")" id="addRow" class="btn btn-info">
                                                            Adicionar <i class="fa fa-plus"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="table-scrollable">
                                                <table class="table table-hover table-checkable order-column full-width" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th> @Html.DisplayNameFor(model => model.Id) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Cpf) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Nome) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Sobrenome) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Data_nascimento) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Sexo) </th>
                                                            <th> Ação </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td> @Html.DisplayFor(modelItem => item.Id) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Cpf) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Nome) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Sobrenome) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Data_nascimento) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Sexo) </td>
                                                                <td>
                                                                    <a href="@Url.Action("Edit_patient", "Receptionist", new { rg = item.Id })" class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->

SIS/SIS/Views/Receptionist/Receptionist_profile.cshtml
@model SIS.Models.Users.Receptionist


@{
    ViewBag.Title = "Minha conta";
    ViewBag.user_type = "Recepcionista";
}}


<script>
    @*function pegaTipoUsuario()
    {
        var tipoUsuario = "Lorem Ipsum";
        if (!(tipoUsuario == null || tipoUsuario == ""))
        {
            if ("@SIS.Models.Users.Hospital.Exists(Request.Cookies.Get("nome").Value)" == "true")
            {
                tipoUsuario = "@Request.Cookies.Get("nome").Value"
            }
            else if ("@SIS.Models.Users.Person.GetTypeByName(Request.Cookies.Get("nome").Value)".length > 0)
            {
                tipoUsuario = "@SIS.Models.Users.Person.GetTypeByName(Request.Cookies.Get("nome").Value)";
            }
        }
        document.getElementById("tipoUsuario").textContent = tipoUsuario;
    }*@

    function insereFotoPerfil() {
        $.post("Home/CarregaFotoPerfil", { nomeUsuario: "@Html.DisplayFor(model => model.Nome)" + " " + "@Html.DisplayFor(model => model.Sobrenome)" }, function (data) {
            if (data.length > 0)
                document.getElementById('fotoPerfil').src = data;
        });
    }


    function insereInformacoesPessoa() {
        alert("Inserção de informações de pessoa!");
    }

    function insereInformacoesHospital() {
        alert("Inserção de informações de hospital!");
    }


</script>

<div class="page-content-wrapper">
    <div class="page-content">

        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Perfil</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="Sair">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    <li class="active">Perfil</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PROFILE SIDEBAR -->
                <div class="profile-sidebar">
                    <div class="card card-topline-aqua">
                        <div class="card-body no-padding height-9">
                            <div class="row">
                                <div class="profile-userpic">
                                    <img src="img/dp.jpg" class="img-responsive" alt="">
                                </div>
                            </div>
                            <div class="profile-usertitle">
                                <div class="profile-usertitle-name"> @ViewBag.PessoaDoPerfil </div>
                                <div class="profile-usertitle-job" id="tipoUsuario"> @ViewBag.user_type </div>
                            </div>
                            <img id="fotoPerfil" src="~/Content/img/imgUsuario.jpg" style="width: 100%; border: 2px solid #949494; border-radius: 5px;" />

                            <br />
                            <br />
                            <br />

                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Gênero </b>
                                    <div class="profile-desc-item pull-right">@Html.DisplayFor(model => model.Sexo)</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- END BEGIN PROFILE SIDEBAR -->
                <!-- BEGIN PROFILE CONTENT -->
                <div class="profile-content" style="width:60%">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-head card-topline-aqua">
                                    <header>INFORMAÇÕES</header>
                                </div>
                                <div class="card-body no-padding height-9">
                                    <div class="container-fluid">
                                        <br />
                                        <div class="row">
                                            <div class="col-md-12">

                                                <div class="activity-desk">
                                                    <h5><a href="">ID</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Id</a> </h5>
                                                    <h5><a href="">CPF</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Cpf</a> </h5>
                                                    <h5><a href="">Data de Nascimento</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;@Model.Data_nascimento_Formatada</a> </h5>
                                                    <h5><a href="">Email</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Email</a> </h5>
                                                    <h5>
                                                        <a href="">Endereço</a> <a class="text-muted">
                                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Endereco_Formatado
                                                        </a>
                                                    </h5>

                                                    <a href="">Telefones</a>
                                                    <ul>
                                                        @foreach (var item in Model.ListaTelefone)
                                                        {
                                                            <li>
                                                                <h5> <a class="text-muted">@item.Numero - @item.Tipo</a> </h5>
                                                            </li>
                                                        }
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END PROFILE CONTENT -->
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('fotoPerfil').src = "@SIS.Controllers.HomeController.CarregaFotoPerfil(Html.DisplayFor(model => model.Nome) + " " + Html.DisplayFor(model => model.Sobrenome))";
</script>

SIS/SIS/Views/Receptionist/TrocarSenha.cshtml
@{
    Layout = "~/Views/Shared/blank_page.cshtml";
    ViewBag.Title = "TrocarSenha";
    ViewBag.user_type = "Recepcionista";
}

<h2>TrocarSenha</h2>