SIS/SIS/Models/Users/People/Administrator/Administrator.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;

namespace SIS.Models.Users
{
    public class Administrator : Person
    {
        /** MÉTODOS DA CLASSE **/
        #region methods

        #region recover_password
        #region get_contact_info
        // --Método desenvolvido para retornar as informações de contato do usuário--
        public static Administrator GetContactInfo(string id)
        {
            // Declaração de variável
            Administrator administrator = null;

            try
            {
                // Abrindo conexão com o banco de dados
                if (con.State == ConnectionState.Closed)
                    con.Open();

                // Comando MySql desenvolvido para selecionar os dados do usuário informado
                MySqlCommand query = new MySqlCommand("select p.email from pessoa p where p.id = @id;", con);
                // Definindo os valores dos parâmetros passados no comando MySql
                query.Parameters.AddWithValue("@id", id);

                // Guardando o retorno do comando efetuado
                MySqlDataReader reader = query.ExecuteReader();

                if (reader.Read())
                {
                    administrator = new Administrator
                    {
                        Email = Convert.ToString(reader["email"])
                    };
                }
                reader.Close();

                if (!administrator.Equals(null))
                {
                    administrator.list_telephones = CatchMobilePhone(id);
                }

                con.Close();
            }
            catch (Exception error)
            {
                string errorMessage = error.Message;
                administrator = null;
                con.Close();
            }

            return administrator;
        }
        #endregion
        #endregion

        #region account_manipulation
        #region view_profile
        // --Método desenvolvido para retornar os dados do administrador autenticado no sistema--
        public static Administrator GetInfo(string id)
        {
            // Declaração de variável
            Administrator administrator = null;

            try
            {
                // Abrindo conexão com o banco de dados
                if (con.State == ConnectionState.Closed)
                    con.Open();

                // Comando MySql desenvolvido para selecionar os dados do usuário autenticado
                MySqlCommand query = new MySqlCommand("select p.id, p.cpf, p.nome, p.sobrenome, p.data_nascimento, p.sexo, p.foto, p.email, cast(aes_decrypt(p.senha, @cryptographyKey) as char) as senha, p.nivel_acesso, " +
                    "e.cep, e.estado, e.cidade, e.bairro, e.rua, e.numero, e.complemento " +
                    "from pessoa p, endereco e " +
                    "where p.id = @id and e.id = p.endereco;", con);
                // Definindo os valores dos parâmetros passados no comando MySql
                query.Parameters.AddWithValue("@id", id);
                query.Parameters.AddWithValue("@cryptographyKey", ConfigurationManager.ConnectionStrings["cryptographyKey"].ConnectionString);

                // Guardando o retorno do comando efetuado
                MySqlDataReader reader = query.ExecuteReader();

                if (reader.Read())
                {
                    administrator = new Administrator
                    {
                        Id = Convert.ToString(reader["id"]),
                        Cpf = Convert.ToString(reader["cpf"]),
                        Nome = Convert.ToString(reader["nome"]),
                        Sobrenome = Convert.ToString(reader["sobrenome"]),
                        Data_nascimento = Convert.ToDateTime(reader["data_nascimento"]),
                        Sexo = Convert.ToString(reader["sexo"]),
                        Email = Convert.ToString(reader["email"]),
                        Senha = Convert.ToString(reader["senha"]),
                        Nivel_acesso = Convert.ToString(reader["nivel_acesso"])
                    };

                    try
                    {
                        administrator.Foto = (byte[])reader["foto"];
                    }
                    catch (Exception error)
                    {
                        string errorMessage = error.Message;
                    }

                    administrator.Endereco.Cep = Convert.ToString(reader["cep"]);
                    administrator.Endereco.Estado = Convert.ToString(reader["estado"]);
                    administrator.Endereco.Cidade = Convert.ToString(reader["cidade"]);
                    administrator.Endereco.Bairro = Convert.ToString(reader["bairro"]);
                    administrator.Endereco.Rua = Convert.ToString(reader["rua"]);
                    administrator.Endereco.Numero = Convert.ToString(reader["numero"]);
                    administrator.Endereco.Complemento = Convert.ToString(reader["complemento"]);
                }
                reader.Close();

                if (!administrator.Equals(null))
                {
                    administrator.list_telephones = Person.CatchTelephone(id);
                }

                con.Close();
            }
            catch (Exception error)
            {
                string errorMessage = error.Message;
                administrator = null;
                con.Close();
            }

            return administrator;
        }
        #endregion
        #endregion

        #endregion
    }
}

SIS/SIS/Controllers/AdministratorController.cs
using SIS.Models.Users;
using System;
using System.Web;
using System.Web.Mvc;

namespace SIS.Controllers
{
    public class AdministratorController : Controller
    {
        public ActionResult Administrator_profile()
        {
            return View("Administrator_profile", (Administrator)Session["usuario"]);
        }

        public ActionResult Change_profile(string id)
        {
            Person pessoa = new Person();
            return View();
        }

        [HttpPost]
        public ActionResult Change_profile(Administrator administrator)
        {
            return View();
        }


        public ActionResult Edit_hospital(string cnes)
        {
            //UTILIZAR O OBJETO USUARIO PARA CHAMAR O MÉTODO BUSCA USUARIO DO MODELO
            Hospital hospital = Hospital.GetInfo(cnes);

            //COMPARAR PARA VER SE ENCONTRAR UM OBJETO IGUAL
            if (hospital == null)
            {
                //MENSAGEM DE CONFIRMAÇÃO
                TempData["Msg"] = "Erro ao buscar o hospital especificado!";
                //RETORNA PARA A VIEW 
                return RedirectToAction("List_hospitals");
            }

            return View(hospital);
        }

        public ActionResult Change_hospital(string cnes)
        {
            //UTILIZAR O OBJETO USUARIO PARA CHAMAR O MÉTODO BUSCA USUARIO DO MODELO
            Hospital hospital = Hospital.GetInfo(cnes);

            //COMPARAR PARA VER SE ENCONTRAR UM OBJETO IGUAL
            if (hospital == null)
            {
                //MENSAGEM DE CONFIRMAÇÃO
                TempData["Msg"] = "Erro ao buscar hospital!";
                //RETORNA PARA A VIEW 
                return RedirectToAction("List_hospitals");
            }
            return View(hospital);
        }

        [HttpPost]
        //CONSTRUTOR COM OS ATRIBUTOS
        public ActionResult Change_hospital(string foto, string email, string telefoneNumero, string estado, string cidade,
                                            string bairro, string cep, string rua, string enderecoNumero, string complemento)
        {
            //CRIANDO OBJETO DE USUARIO
            Hospital hospital = new Hospital();

            //ATRIBUINDO O VALORES 
            //hospital.Foto = (byte[])foto;
            hospital.Email = email;
            hospital.Telephones.Numero = telefoneNumero;
            hospital.Endereco.Estado = estado;
            hospital.Endereco.Cidade = cidade;
            hospital.Endereco.Cep = cep;
            hospital.Endereco.Bairro = bairro;
            hospital.Endereco.Rua = rua;
            hospital.Endereco.Numero = enderecoNumero;
            hospital.Endereco.Complemento = complemento;

            try
            {
                HttpPostedFileBase arqPostado = Request.Files[foto];

                int tamImagem = arqPostado.ContentLength; //pega o tamanho
                string tipoArq = arqPostado.ContentType; //pega o tipo

                if (tipoArq.IndexOf("jpeg") > 0 || tipoArq.IndexOf("png") > 0)
                {
                    byte[] imgBytes = new byte[tamImagem];
                    arqPostado.InputStream.Read(imgBytes, 0, tamImagem);

                    hospital.Foto = imgBytes;
                }
            }
            catch (Exception erro)
            {
                string msgErro = erro.Message;
            }

            //CHAMA MÉTODO DO MODELO
            string res = hospital.Editar();
            TempData["Msg"] = res;
            // COMPARA SE ESTA CORRETO E APRESENTA A MENSAGEM DE CONFIRMAÇÃO
            if (res == "Salvo com sucesso!")
                //RETORNA PARA A VIEW 
                return RedirectToAction("List_hospitals");
            else
                return View();
        }


        public ActionResult Administrador()
        {
            return View();
        }

        // --FUNCIONANDO--
        public ActionResult List_hospitals()
        {
            return View(Hospital.List_hospitals());
        }

        public ActionResult Register_hospital()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register_hospital(string cnes, string cnpj, string nome, string razaosocial, string foto, string email, string senha,
                                             string telefoneNumero, string telefoneTipo, string estado, string cidade, string bairro, string cep,
                                             string rua, string enderecoNumero, string complemento)
        {

            //CRIANDO OBJETO DE USUARIO
            Hospital hospital = new Hospital();

            //ATRIBUINDO OS VALORES 
            hospital.Cnes = cnes;
            hospital.Cnpj = cnpj;
            hospital.Nome_fantasia = nome;
            hospital.Razao_social = razaosocial;
            hospital.Email = email;
            hospital.Senha = senha;
            hospital.Telephones.Numero = telefoneNumero;
            hospital.Telephones.Tipo = telefoneTipo;
            hospital.Endereco.Estado = estado;
            hospital.Endereco.Cidade = cidade;
            hospital.Endereco.Cep = cep;
            hospital.Endereco.Bairro = bairro;
            hospital.Endereco.Rua = rua;
            hospital.Endereco.Numero = enderecoNumero;
            hospital.Endereco.Complemento = complemento;

            try
            {
                HttpPostedFileBase arqPostado = Request.Files[0];

                int tamImagem = arqPostado.ContentLength; //pega o tamanho
                string tipoArq = arqPostado.ContentType; //pega o tipo

                if (tipoArq.IndexOf("jpeg") > 0 || tipoArq.IndexOf("png") > 0)
                {
                    byte[] imgBytes = new byte[tamImagem];
                    arqPostado.InputStream.Read(imgBytes, 0, tamImagem);

                    hospital.Foto = imgBytes;
                }
            }
            catch (Exception erro)
            {
                string msgErro = erro.Message;
            }

            // CHAMA MÉTODO DO CONTROLLER
            TempData["Msg"] = hospital.Register();

            //MENSAGEM DE CONFIRMAÇÃO
            return RedirectToAction ("List_hospitals");
        }

        public ActionResult DeleteHospital(string id)
        {
            //CRIANDO OBJETO DE USUARIO
            Hospital hospital = new Hospital();
            //ATRIBUINDO O VALORES 
            hospital.Cnes = id;
            //CHAMA MÉTODO DO CONTROLLER
            hospital.Remover();
            //MENSAGEM DE CONFIRMAÇÃO
            return RedirectToAction("List_hospitals");
        }

        public ActionResult Perfil(string id)
        {
            ViewBag.PessoaDoPerfil = id;
            return View();
        }

        public ActionResult TrocarSenha()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TrocarSenha(string id)
        {
            return View();
        }

        public ActionResult Sair() // Apaga os cookies e volta para a tela de login
        {
            int aux = Request.Cookies.Count; // Para evitar loop :P
            string[] nomes = Request.Cookies.AllKeys; // Para chamar um cookie específico
            for (int i = 0; i < aux; i++)
            {
                HttpCookie myCookie = new HttpCookie(nomes[i]);
                myCookie.Expires = DateTime.Now.AddDays(-1d);
                Response.Cookies.Add(myCookie);
            }
            Request.Cookies.Clear(); // Limpa os cookies do servidor, mas não os da máquina do cliente

            return RedirectToAction("Login", "Home");
        }
    }
}

SIS/SIS/Views/Administrator/Administrator_profile.cshtml
@model SIS.Models.Users.Administrator


@{
    ViewBag.Title = "Minha conta";
    ViewBag.user_type = "Administrador";
}}


<script>
    @*function pegaTipoUsuario()
    {
        var tipoUsuario = "Lorem Ipsum";
        if (!(tipoUsuario == null || tipoUsuario == ""))
        {
            if ("@SIS.Models.Users.Hospital.Exists(Request.Cookies.Get("nome").Value)" == "true")
            {
                tipoUsuario = "@Request.Cookies.Get("nome").Value"
            }
            else if ("@SIS.Models.Users.Person.GetTypeByName(Request.Cookies.Get("nome").Value)".length > 0)
            {
                tipoUsuario = "@SIS.Models.Users.Person.GetTypeByName(Request.Cookies.Get("nome").Value)";
            }
        }
        document.getElementById("tipoUsuario").textContent = tipoUsuario;
    }*@

    function insereFotoPerfil() {
        $.post("Home/CarregaFotoPerfil", { nomeUsuario: "@Html.DisplayFor(model => model.Nome)" + " " + "@Html.DisplayFor(model => model.Sobrenome)" }, function (data) {
            if (data.length > 0)
                document.getElementById('fotoPerfil').src = data;
        });
    }


    function insereInformacoesPessoa() {
        alert("Inserção de informações de pessoa!");
    }

    function insereInformacoesHospital() {
        alert("Inserção de informações de hospital!");
    }


</script>

<div class="page-content-wrapper">
    <div class="page-content">

        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Perfil</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="Sair">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    <li class="active">Perfil</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PROFILE SIDEBAR -->
                <div class="profile-sidebar">
                    <div class="card card-topline-aqua">
                        <div class="card-body no-padding height-9">
                            <div class="row">
                                <div class="profile-userpic">
                                    <img src="img/dp.jpg" class="img-responsive" alt="">
                                </div>
                            </div>
                            <div class="profile-usertitle">
                                <div class="profile-usertitle-name"> @ViewBag.PessoaDoPerfil </div>
                                <div class="profile-usertitle-job" id="tipoUsuario"> @ViewBag.user_type </div>
                            </div>
                            <img id="fotoPerfil" src="~/Content/img/imgUsuario.jpg" style="width: 100%; border: 2px solid #949494; border-radius: 5px;" />

                            <br />
                            <br />
                            <br />

                            <ul class="list-group list-group-unbordered">
                                <li class="list-group-item">
                                    <b>Gênero </b>
                                    <div class="profile-desc-item pull-right">@Html.DisplayFor(model => model.Sexo)</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- END BEGIN PROFILE SIDEBAR -->
                <!-- BEGIN PROFILE CONTENT -->
                <div class="profile-content" style="width:60%">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-head card-topline-aqua">
                                    <header>INFORMAÇÕES</header>
                                </div>
                                <div class="card-body no-padding height-9">
                                    <div class="container-fluid">
                                        <br />
                                        <div class="row">
                                            <div class="col-md-12">

                                                <div class="activity-desk">
                                                    <h5><a href="">ID</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.Id)</a> </h5>
                                                    <h5><a href="">CPF</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.Cpf)</a> </h5>
                                                    <h5><a href="">Data de Nascimento</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.Data_nascimento_Formatada)</a> </h5>
                                                    <h5><a href="">Email</a> <a class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.Email)</a> </h5>
                                                    <h5>
                                                        <a href="">Endereço</a> <a class="text-muted">
                                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.DisplayFor(model => model.Endereco_Formatado)
                                                        </a>
                                                    </h5>

                                                    <a href="">Telefones</a>
                                                    <ul>
                                                        @foreach (var item in Model.ListaTelefone)
                                                        {
                                                            <li>
                                                                <h5> <a class="text-muted">@Html.DisplayFor(modelItem => item.Numero) - @Html.DisplayFor(modelItem => item.Tipo)</a> </h5>
                                                            </li>
                                                        }
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END PROFILE CONTENT -->
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('fotoPerfil').src = "@SIS.Controllers.HomeController.CarregaFotoPerfil(Html.DisplayFor(model => model.Nome) + " " + Html.DisplayFor(model => model.Sobrenome))";
</script>

SIS/SIS/Views/Administrator/Change_hospital.cshtml
@model SIS.Models.Users.Hospital

@{
    Layout = "~/Views/Shared/blank_page.cshtml";
    ViewBag.Title = "Altera Hospital";
    ViewBag.user_type = "Administrador";
}

<h2>AlteraDadosHospital</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hospital</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cnes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cnes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cnes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cnpj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cnpj, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cnpj, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome_fantasia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome_fantasia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome_fantasia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Razao_social, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Razao_social, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Razao_social, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SIS/SIS/Views/Administrator/List_hospitals.cshtml
@model IEnumerable<SIS.Models.Users.Hospital>

@{
    ViewBag.Title = "Listar hospitais";
    ViewBag.user_type = "Administrador";
}

<!-- start page content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Listar Hospitais</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li>
                        <i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="@Url.Action("Sair", "Home")">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a class="parent-item" href="">Hospitais</a>&nbsp;<i class="fa fa-angle-right"></i>
                    </li>
                    <li class="active">Listar hospitais</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <ul class="nav customtab nav-tabs" role="tablist">
                        <li class="nav-item"><a href="#tab1" class="nav-link active" data-toggle="tab">Ver lista</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-topline-red">
                                        <div class="card-head">
                                            <header></header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6 col-xs-6">
                                                    <div class="btn-group">
                                                        <a href="@Url.Action("Register_hospital", "Administrator")" id="addRow" class="btn btn-info">
                                                            Adicionar <i class="fa fa-plus"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="table-scrollable">
                                                <table class="table table-hover table-checkable order-column full-width" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th> @Html.DisplayNameFor(model => model.Cnes) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Cnpj) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Nome_fantasia) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Razao_social) </th>
                                                            <th> Ação </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td> @Html.DisplayFor(modelItem => item.Cnes) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Cnpj) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Nome_fantasia) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Razao_social) </td>
                                                                <td>
                                                                    <a href="@Url.Action("Edit_hospital", "Administrator", new { cnes = item.Cnes })" class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                    <a href="javascript()" class="btn btn-danger btn-xs">
                                                                        <i class="fa fa-trash-o "></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->