SIS/SIS/Models/Users/People/Doctor/Doctor.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;

namespace SIS.Models.Users
{
    public class Doctor : Person
    {
        /** DECLARAÇÃO DOS ATRIBUTOS DA CLASSE **/
        #region parameters
        // --Objetos instanciados para ligação entre as tabelas no banco de dados--
        private Occupation_Area area_atuacao = new Occupation_Area();
        private List<Medical_Specialty> list_medical_specialties = new List<Medical_Specialty>();
        private Medical_Specialty especialidade = new Medical_Specialty();

        /** Como nenhum dos atributos pode ser acessado ou modificado diretamente por alguma outra classe, criam-se 
        variavéis que serão as pontes para acessá-los e modificá-los (Getters e Setters)**/
        // --Atributos da tabela 'pessoa'--
        [Required(ErrorMessage = "Obrigatório informar o CRM")]
        [StringLength(13, ErrorMessage = "O CRM deve possuir no máximo 13 caracteres")]
        [Display(Name = "CRM")]
        public string Crm
        {
            get { return id; }
            set { id = value; }
        }

        // --Objetos instanciados para ligação entre as tabelas no banco de dados--
        public Occupation_Area Area_atuacao
        {
            get { return area_atuacao; }
            set { area_atuacao = value; }
        }

        public List<Medical_Specialty> List_medical_specialties
        {
            get { return list_medical_specialties; }
            set { list_medical_specialties = value; }
        }

        public Medical_Specialty Especialidade
        {
            get { return especialidade; }
            set { especialidade = value; }
        }
        #endregion

        /** MÉTODOS DA CLASSE **/
        #region methods

        #region recover_password
        #region get_contact_info
        // --Método desenvolvido para retornar as informações de contato do usuário--
        public static Doctor GetContactInfo(string crm)
        {
            // Declaração de variável
            Doctor doctor = null;

            try
            {
                // Abrindo conexão com o banco de dados
                if (con.State == ConnectionState.Closed)
                    con.Open();

                // Comando MySql desenvolvido para selecionar os dados do usuário informado
                MySqlCommand query = new MySqlCommand("select p.email from pessoa p where p.id = @crm;", con);
                // Definindo os valores dos parâmetros passados no comando MySql
                query.Parameters.AddWithValue("@crm", crm);

                // Guardando o retorno do comando efetuado
                MySqlDataReader reader = query.ExecuteReader();

                if (reader.Read())
                {
                    doctor = new Doctor
                    {
                        Email = Convert.ToString(reader["email"])
                    };
                }
                reader.Close();

                if (!doctor.Equals(null))
                {
                    doctor.list_telephones = CatchMobilePhone(crm);
                }

                con.Close();
            }
            catch (Exception error)
            {
                string errorMessage = error.Message;
                doctor = null;
                con.Close();
            }

            return doctor;
        }
        #endregion
        #endregion

        #region account_manipulation
        #region register_doctor
        // --Método desenvolvido para cadastrar um(a) novo(a) médico(a) no sistema--
        public bool Register()
        {
            // Declaração de variável
            bool result = false;
            // Cadastrando o endereço do usuário, caso necessário, e recebendo o valor do id do mesmo
            endereco.Id = endereco.GetAddress();


            try
            {
                // Abrindo conexão com o banco de dados
                if (con.State == ConnectionState.Closed)
                    con.Open();

                // Comando MySql desenvolvido para adicionar um registro na tabela 'pessoa' do banco de dados
                MySqlCommand query = new MySqlCommand("insert into pessoa(id, cpf, nome, sobrenome, data_nascimento, sexo, foto, email, senha, nivel_acesso, area_atuacao, endereco) " +
                    "values(@id, @cpf, @nome, @sobrenome, @data_nascimento, @sexo, @foto, @email, aes_encrypt(@senha, @cryptographyKey), @nivel_acesso, @area_atuacao, @endereco)", con);
                // Definindo os valores dos parâmetros passados no comando MySql
                query.Parameters.AddWithValue("@id", id);
                query.Parameters.AddWithValue("@cpf", cpf);
                query.Parameters.AddWithValue("@nome", nome);
                query.Parameters.AddWithValue("@sobrenome", sobrenome);
                query.Parameters.AddWithValue("@data_nascimento", data_nascimento);
                query.Parameters.AddWithValue("@sexo", sexo);
                query.Parameters.AddWithValue("@foto", foto);
                query.Parameters.AddWithValue("@email", email);
                query.Parameters.AddWithValue("@senha", senha);
                query.Parameters.AddWithValue("@cryptographyKey", ConfigurationManager.ConnectionStrings["cryptographyKey"].ConnectionString);
                query.Parameters.AddWithValue("@nivel_acesso", nivel_acesso);
                query.Parameters.AddWithValue("@area_atuacao", area_atuacao);
                query.Parameters.AddWithValue("@endereco", endereco.Id);

                // Executando o comando MySQL elaborado
                query.ExecuteNonQuery();

                // Cadastrando os telefones do usuário, caso necessário, e conectando-os ao mesmo no banco de dados
                foreach (Telephone telephone in list_telephones)
                {
                    telephone.Register_user_telephone(id);
                }
                especialidade.RegisterSpecialty();
                InsertDoctorSpeciality(id);

                result = true;

                con.Close();
            }
            catch (Exception error)
            {
                string errorMessage = error.Message;
                result = false;
                con.Close();
            }

            return result;
        }
        #endregion

        #region view_profile
        // --Método desenvolvido para retornar os dados do médico autenticado no sistema--
        public static Doctor GetInfo(string crm)
        {
            MySqlConnection con = new MySqlConnection(ConfigurationManager.ConnectionStrings["BCD"].ConnectionString);
            // Declaração de variável
            Doctor doctor = null;

            try
            {
                // Abrindo conexão com o banco de dados
                if (con.State == ConnectionState.Closed)
                    con.Open();

                // Comando MySql desenvolvido para selecionar os dados do usuário autenticado
                MySqlCommand query = new MySqlCommand("select p.id, p.cpf, p.nome, p.sobrenome, p.data_nascimento, p.sexo, p.foto, p.email, cast(aes_decrypt(p.senha, @cryptographyKey) as char) as senha, p.nivel_acesso, p.area_atuacao, " +
                    "e.cep, e.estado, e.cidade, e.bairro, e.rua, e.numero, e.complemento " +
                    "from pessoa p, endereco e " +
                    "where p.id = @crm and e.id = p.endereco;", con);
                // Definindo os valores dos parâmetros passados no comando MySql
                query.Parameters.AddWithValue("@cryptographyKey", ConfigurationManager.ConnectionStrings["cryptographyKey"].ConnectionString);
                query.Parameters.AddWithValue("@crm", crm);

                // Guardando o retorno do comando efetuado
                MySqlDataReader reader = query.ExecuteReader();

                if (reader.Read())
                {
                    doctor = new Doctor
                    {
                        Id = Convert.ToString(reader["id"]),
                        Cpf = Convert.ToString(reader["cpf"]),
                        Nome = Convert.ToString(reader["nome"]),
                        Sobrenome = Convert.ToString(reader["sobrenome"]),
                        Data_nascimento = Convert.ToDateTime(reader["data_nascimento"]),
                        Sexo = Convert.ToString(reader["sexo"]),
                        Email = Convert.ToString(reader["email"]),
                        Senha = Convert.ToString(reader["senha"]),
                        Nivel_acesso = Convert.ToString(reader["nivel_acesso"])
                    };

                    try
                    {
                        doctor.Foto = (byte[])reader["foto"];
                    }
                    catch (Exception error)
                    {
                        string errorMessage = error.Message;
                    }

                    doctor.Area_atuacao.Id = int.Parse(Convert.ToString(reader["area_atuacao"]));
                    doctor.Endereco.Cep = Convert.ToString(reader["cep"]);
                    doctor.Endereco.Estado = Convert.ToString(reader["estado"]);
                    doctor.Endereco.Cidade = Convert.ToString(reader["cidade"]);
                    doctor.Endereco.Bairro = Convert.ToString(reader["bairro"]);
                    doctor.Endereco.Rua = Convert.ToString(reader["rua"]);
                    doctor.Endereco.Numero = Convert.ToString(reader["numero"]);
                    doctor.Endereco.Complemento = Convert.ToString(reader["complemento"]);
                }
                reader.Close();

                if (!doctor.Equals(null))
                {
                    doctor.list_telephones = Person.CatchTelephone(crm);
                    doctor.list_medical_specialties = Doctor.CatchMedicalSpecialty(crm);
                }

                con.Close();
            }
            catch (Exception error)
            {

SIS/SIS/Controllers/DoctorController.cs
using SIS.Models;
using SIS.Models.Users;
using SIS.Models.Users.Agenda;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace SIS.Controllers
{
    public class DoctorController : Controller
    {
        #region profile
        public ActionResult Doctor_profile()
        {
            return View("Doctor_profile", (Doctor)Session["usuario"]);
        }
        #endregion

        ////---------------------------------METODO ALTERAR-----------------------------------//
        //public ActionResult AlterarMedico(string id)
        //{
        //    //UTILIZAR O OBJETO USUARIO PARA CHAMAR O MÉTODO BUSCA USUARIO DO MODELO
        //    List<Doctor> doutor = Doctor.ListaMedico(id);
        //    //COMPARAR PARA VER SE ENCONTRAR UM OBJETO IGUAL
        //    if (doutor == null)
        //    {
        //        //MENSAGEM DE CONFIRMAÇÃO
        //        TempData["Msg"] = "Erro ao buscar Médico!";
        //        //RETORNA PARA A VIEW 
        //        return RedirectToAction("ListarMedicos");
        //    }
        //    return View(doutor);
        //}

        //---------------------------------METODO ALTERAR-----------------------------------//
        [HttpPost]
        // CONSTRUTOR COM OS ATRIBUTOS
        public ActionResult AlterarMedico(string nome, string sobrenome, string sexo, string email,
                                          string area_atuacao, DateTime data_nascimento, byte[] foto, string telefoneNumero)
        {
            //CRIANDO OBJETO DE USUARIO
            Doctor doutor = new Doctor();
            Telephone telephone = new Telephone();

            //ATRIBUINDO O VALORES 
            doutor.Nome = nome;
            doutor.Sobrenome = sobrenome;
            doutor.Sexo = sexo;
            doutor.Email = email;
            //doutor.Area_atuacao = area_atuacao;
            doutor.Data_nascimento = data_nascimento;
            doutor.Foto = foto;
            //telephone.Numero = telefoneNumero;
            
            //CHAMA MÉTODO DO MODELO
            string res = doutor.Editar();
            TempData["Msg"] = res;
            // COMPARA SE ESTA CORRETO E APRESENTA A MENSAGEM DE CONFIRMAÇÃO
            if (res == "Salvo com sucesso!")
                //RETORNA PARA A VIEW 
                return RedirectToAction("ListarMedicos");
            else
                return View();
        }

        //---------------------------------METODO LISTAR-----------------------------------//
        public ActionResult List_patients()
        {
            // ATRIBUI A VIEW A LISTAR USUARIOS E APRESENTA TODOS USUARIOS DA LISTA
            return View(Patient.List_patients());
        }

        //-----------------------MÉTODO ADICIONAR DOCUMENTAÇÃO PACIENTE APOS CONSULTA MÉDICA---------------------//
        public ActionResult AdicionarRelatorio(string paciente)
        {
            return View();
        }


        public ActionResult Perfil(string id)
        {
            ViewBag.PessoaDoPerfil = id;
            return View();
        }
        
        public ActionResult TrocarSenha()
        {
            return View();
        }

        public ActionResult Sair() // Apaga os cookies e volta para a tela de login
        {
            int aux = Request.Cookies.Count; // Para evitar loop :P
            string[] nomes = Request.Cookies.AllKeys; // Para chamar um cookie específico
            for (int i = 0; i < aux; i++)
            {
                HttpCookie myCookie = new HttpCookie(nomes[i]);
                myCookie.Expires = DateTime.Now.AddDays(-1d);
                Response.Cookies.Add(myCookie);
            }
            Request.Cookies.Clear(); // Limpa os cookies do servidor, mas não os da máquina do cliente

            return RedirectToAction("Login", "Home");
        }
        
        public ActionResult List_Appointment()
        {
            return View(Agenda.listaConsultas());
        }

        public ActionResult List_exames()
        {
            return View(Agenda.listaExames());
        }

        public ActionResult Remove_Appointment(string id)
        {
            Appointment.CancelarConsulta(id);

            return RedirectToAction("List_Appointment");
        }

        public ActionResult Continue_Appointment(string id)
        {
            Session.Add("consultaAtual", id);
            return View(Agenda.VisualizarConsulta(id));
        }

        [HttpPost]
        public ActionResult Continue_Appointment(string observacao, string medicamento, string quantidade, string duracao, string descricao)
        {
            string idConsulta = Session["consultaAtual"].ToString();

            PrescricaoMedica prescricao = null;
            Exame exame = null;

            if(medicamento != null && quantidade != null && duracao != null)
            {
                prescricao = new PrescricaoMedica();
                prescricao.Consulta = idConsulta;
                prescricao.Medicamento = medicamento;
                prescricao.Quantidade = quantidade;
                prescricao.Duracao = duracao;
            }

            if(descricao != null)
            {
                exame = new Exame();
                exame.Descricao = descricao;
            }

            Appointment.ConfirmaConsulta(idConsulta, observacao, prescricao, exame);

            return RedirectToAction("List_Appointment");
        }


        public ActionResult Remove_Exame(string id)
        {
            Exame.CancelarExame(id);

            return RedirectToAction("List_exames");
        }


        public ActionResult Finish_Exame(string id)
        {
            Session.Add("exameAtual", id);
            return View(Agenda.VisualizarExame(id));
        }

        [HttpPost]
        public ActionResult Finish_Exame(string observacao, string foto)
        {
            string idExame = Session["exameAtual"].ToString();
            byte[] documento_resultado = null;

            try
            {
                HttpPostedFileBase arqPostado = Request.Files[0];

                int tamImagem = arqPostado.ContentLength; //pega o tamanho
                string tipoArq = arqPostado.ContentType; //pega o tipo

                if (tipoArq.IndexOf("jpeg") > 0 || tipoArq.IndexOf("png") > 0)
                {
                    byte[] imgBytes = new byte[tamImagem];
                    arqPostado.InputStream.Read(imgBytes, 0, tamImagem);

                    documento_resultado = imgBytes;
                }
            }

            catch (Exception erro)
            {
                string msgErro = erro.Message;
            }

            Exame.ConcluirExame(idExame, documento_resultado, observacao);
            return RedirectToAction("List_exames");
        }

        public ActionResult View_Exame(string id)
        {
            return View(Agenda.VisualizarExame(id));
        }
    }
}

SIS/SIS/Views/Doctor/AlteraMedico.cshtml
@{
    ViewBag.Title = "AlteraMedico";
    ViewBag.user_type = "Médico";
}

<h2>AlteraMedico</h2>

SIS/SIS/Views/Doctor/Finish_Exame.cshtml
@model SIS.Models.Users.Agenda.Exame

@{
    ViewBag.Title = "Completar exame";
    ViewBag.User = "Recepcionista";
    ViewBag.user_type = "Médico";
}

<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card card-box">
                    <div class="card-head">
                        <header>Conclusão do exame</header>
                        <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                            data-mdl-for="panel-button">
                            <li class="mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                            <li class="mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                            <li class="mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                        </ul>
                    </div>
                    <div class="card-body" id="bar-parent">
                        <form action="Register_appointment" id="form_sample_1" class="form-horizontal" method="post" enctype="multipart/form-data">
                            <br />
                            <div class="form-body">
                                <div class="form-group row">
                                    <label class="control-label col-md-3">
                                        Observações
                                    </label>
                                    <div class="col-md-5">
                                        <input type="text" name="observacao" id="observacao" data-required="1" placeholder="Observações" class="form-control input-height" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-md-3">
                                    Resultado do exame
                                </label>
                                <input type="file" id="foto" class="default" name="foto">
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="offset-md-3 col-md-9">
                                        <button type="submit" class="btn btn-info m-r-20">Agendar consulta</button>
                                        <button type="button" class="btn btn-default">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SIS/SIS/Views/Doctor/List_Appointment.cshtml
@model IEnumerable<SIS.Models.Users.Agenda.Appointment>

@{
    ViewBag.Title = "Minha conta";
    ViewBag.user_type = "Médico";
}}

<!-- start page content -->
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="Sair">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    <li class="active">Agenda</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-topline-red">
                                        <div class="card-head">
                                            <header></header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="table-scrollable">
                                                <table class="table table-hover table-checkable order-column full-width" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th> @Html.DisplayNameFor(model => model.Data) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Especialidade) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Titulo) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Comentario) </th>
                                                            <th> Ação </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td> @Html.DisplayFor(modelItem => item.Data) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Especialidade) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Titulo) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Comentario) </td>
                                                                <td>
                                                                    <a href="@Url.Action("Continue_Appointment", "Doctor", new { id = item.Codigo })" class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                    <a href="@Url.Action("Remove_Appointment", "Doctor", new { id = item.Codigo })" class="btn btn-danger btn-xs">
                                                                        <i class="fa fa-trash-o "></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->

SIS/SIS/Views/Doctor/List_exames.cshtml
@model IEnumerable<SIS.Models.Users.Agenda.Exame>

@{
    ViewBag.Title = "Minha conta";
    ViewBag.user_type = "Médico";
}}

<!-- start page content -->
<div class="page-content-wrapper">
    <div class="page-content">

        <div class="page-bar">
            <div class="page-title-breadcrumb">
                <div class=" pull-left">
                    <div class="page-title">Perfil</div>
                </div>
                <ol class="breadcrumb page-breadcrumb pull-right">
                    <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="Sair">Sair</a>&nbsp;<i class="fa fa-angle-right"></i>
                    <li class="active">Agenda</li>
                </ol>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card card-topline-red">
                                        <div class="card-head">
                                            <header></header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="table-scrollable">
                                                <table class="table table-hover table-checkable order-column full-width" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th style="min-width:300px"> @Html.DisplayNameFor(model => model.Descricao) </th>
                                                            <th> @Html.DisplayNameFor(model => model.Observacoes) </th>
                                                            <th> Consulta </th>
                                                            <th> @Html.DisplayNameFor(model => model.Concluido) </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td> @Html.DisplayFor(modelItem => item.Descricao) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Observacoes) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Consulta.Titulo) </td>
                                                                <td> @Html.DisplayFor(modelItem => item.Concluido) </td>
                                                                <td>
                                                                    <a href="@Url.Action("View_Exame", "Doctor", new { id = item.ID })" class="btn btn-primary btn-x">
                                                                        <i class="material-icons">assignment</i>
                                                                    </a>
                                                                    @if (!item.Concluido)
                                                                    {
                                                                        <a href="@Url.Action("Finish_Exame", "Doctor", new { id = item.ID })" class="btn btn-primary btn-xs">
                                                                            <i class="fa fa-pencil"></i>
                                                                        </a>
                                                                        <a href="@Url.Action("Remove_Exame", "Doctor", new { id = item.ID })" class="btn btn-danger btn-xs">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </a>
                                                                    }

                                                                </td>
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end page content -->